import directionImg from '../img/departments/direction.jpg';
import marketingImg from '../img/departments/marketing.jpg';
import salesImg from '../img/departments/sales.jpg';
import humanResourcesImg from '../img/departments/humanResources.jpg';
import accountingImg from '../img/departments/accounting.jpg';
import customerCareImg from '../img/departments/customerCare.jpg';
import developersImg from '../img/departments/developers.jpg';

export const INITIAL_STATE_TICKETS = {
  tickets: [
    {
      id: '8',
      createdOn: 'Mon Jun 01 2020 08:30:37 GMT-0400',
      createdBy: 'Denver Firth',
      subject: 'Patterns',
      description: 'We should release the latest patterns soon.',
      priority: 'normal',
      status: 'open',
      department: 'Marketing',
      logs: [
        {
          updatedOn: 'Mon Jun 01 2020 09:00:38 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'This is being handled in first stages.',
          changeOfStatus: [true, 'high', 'normal'],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '9',
      createdOn: 'Mon Jun 01 2020 09:01:32 GMT-0400',
      createdBy: 'Julia Tyrone',
      subject: 'Latest leads',
      description:
        'Happy to release the latest leads. Make sure you sign the form once you get them.',
      priority: 'normal',
      status: 'closed',
      department: 'Customer Care',
      logs: [
        {
          updatedOn: 'Mon Jun 01 2020 09:11:00 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'This should now go to customer care.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [true, 'Marketing', 'Customer Care'],
        },
      ],
    },
    {
      id: '10',
      createdOn: 'Mon Jun 01 2020 09:21:15 GMT-0400',
      createdBy: 'Julia Tyrone',
      subject: 'Design patterns',
      description:
        "We need more details on the latest design pattern DP-8 as it's not documented at all on our end and the product needs to go live in December. The API is done, but we are holding on to push this to FE.",
      priority: 'high',
      status: 'open',
      department: 'Sales',
      logs: [
        {
          updatedOn: 'Mon Jun 01 2020 09:40:30 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'On the way',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
        {
          updatedOn: 'Wed Jun 10 2020 10:55:53 GMT-0400',
          updatedBy: 'Martin Maltais',
          body: 'We are still waiting for this on our end!',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '11',
      createdOn: 'Mon Jun 01 2020 09:59:37 GMT-0400',
      createdBy: 'Trevor Holds',
      subject: 'Better documentation',
      description:
        'Can we get better documentation on the latest procedures regarding the new JTV product? We receive a lot of demand that we are not equipped to handle right now',
      priority: 'high',
      status: 'on hold',
      department: 'Marketing',
      logs: [
        {
          updatedOn: 'Mon Jun 01 2020 10:10:27 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'Waiting for direction regarding the process.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '12',
      createdOn: 'Mon Jun 01 2020 10:40:15 GMT-0400',
      createdBy: 'Martin Martin',
      subject: 'Make money!',
      description:
        'We have the go from the direction to heighten the referral bonus by 10%!',
      priority: 'normal',
      status: 'open',
      department: 'Developers',
      logs: [
        {
          updatedOn: 'Mon Jun 01 2020 10:41:37 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'No answer yet',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '13',
      createdOn: 'Tue Jun 02 2020 15:15:10 GMT-0400',
      createdBy: 'Joey Trebionny',
      subject: 'Annual audit',
      description:
        'To get prepared to the annual audit, everyone needs to fill-in the DW-T6 form in Sharepoint by next September.',
      priority: 'normal',
      status: 'open',
      department: 'Human Resources',
      logs: [
        {
          updatedOn: 'Wed Jun 03 2020 09:48:57 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'Passed on to supervisor',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '14',
      createdOn: 'Thu Jun 04 2020 13:27:52 GMT-0400',
      createdBy: 'Melissa Tender',
      subject: 'Computer upgrades',
      description:
        'The situation in the loft is unacceptable. Upgrades to all computers are now mandatory.',
      priority: 'high',
      status: 'open',
      department: 'Accounting',
      logs: [
        {
          updatedOn: 'Fri Jun 05 2020 11:11:15 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'This needs escalation.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
        {
          updatedOn: 'Tue Jun 09 2020 09:21:42 GMT-0400',
          updatedBy: 'Administrator',
          body: 'Received on our end.\n\nRequest sent, waiting for an update.',
          changeOfStatus: [true, 'open', 'on hold'],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      id: '15',
      createdOn: 'Sat Jun 06 2020 11:00:29 GMT-0400',
      createdBy: 'Sylvio Gutry',
      subject: 'Empty desks and positions to fill',
      description:
        'Since the expansion, we have a minimum of 10 positions to fill.',
      priority: 'high',
      status: 'closed',
      department: 'Sales',
      logs: [
        {
          updatedOn: 'Sun Jun 07 2020 10:43:22 GMT-0400',
          updatedBy: 'Joey Trebionny',
          body: 'We need this soon.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
        {
          updatedOn: 'Sun Jun 07 2020 11:00:25 GMT-0400',
          updatedBy: 'Trevor Holds',
          body: 'Moved to direction.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
        {
          updatedOn: 'Sun Jun 07 2020 12:00:15 GMT-0400',
          updatedBy: 'Martin Martin',
          body: 'This can now be closed.',
          changeOfStatus: [true, 'open', 'closed'],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
    },
    {
      createdOn: 'Mon Jun 08 2020 12:41:37 GMT-0400',
      createdBy: 'Administrator',
      subject: 'Awards for best performance by an agent',
      description:
        'I would like to know the status on that matter, as it was stated in the last staff meeting.',
      priority: 'normal',
      status: 'open',
      department: 'Customer Care',
      logs: [],
      id: 'LGfLHrP',
    },
    {
      createdOn: 'Mon Jun 08 2020 13:40:05 GMT-0400',
      createdBy: 'Administrator',
      subject: 'New API',
      description:
        'The work on the new API has started and we are quite happy with the progress. However, in order to further process it, we need the following:\n\n- Markdown support\n- Simple UI to sort through the documentation\n\nLet me know what can be done,',
      priority: 'low',
      status: 'open',
      department: 'Developers',
      logs: [
        {
          updatedOn: 'Wed Jun 10 2020 09:27:21 GMT-0400',
          updatedBy: 'Dever Firth',
          body:
            'For some reasons, this has been overlooked in the past. I will look into it.',
          changeOfStatus: [false, null, null],
          changeOfPriority: [true, 'normal', 'high'],
          transfer: [false, null, null],
        },
        {
          updatedOn: 'Wed Jun 10 2020 10:26:21 GMT-0400',
          updatedBy: 'Deborah Hill',
          body: "Let's test this!",
          changeOfStatus: [false, null, null],
          changeOfPriority: [false, null, null],
          transfer: [false, null, null],
        },
      ],
      id: '3iuxdEv',
    },
    {
      createdOn: 'Tue Jun 09 2020 05:45:32 GMT-0400',
      createdBy: 'Administrator',
      subject: 'New incentives coming',
      description:
        'As a lot of you have asked us, we are ready to send you the new incentives package. Stay tuned and monitor your emails for the new release!',
      priority: 'normal',
      status: 'on hold',
      department: 'Human Resources',
      logs: [],
      id: 'XSALBSs',
    },
    {
      createdOn: 'Tue Jun 09 2020 05:51:09 GMT-0400',
      createdBy: 'Manager',
      subject: 'We need more people!',
      description:
        "I know that this is currently an active situation, but I don't know if there is any follow up on this issue?",
      priority: 'high',
      status: 'open',
      department: 'Human Resources',
      logs: [],
      id: 'Ygf6CBZ',
    },
    {
      createdOn: 'Tue Jun 09 2020 05:53:18 GMT-0400',
      createdBy: 'User',
      subject: 'T4',
      description: 'When do we get our T4?',
      priority: 'normal',
      status: 'open',
      department: 'Accounting',
      logs: [],
      id: 'J-rfvrL',
    },
    {
      createdOn: 'Wed Jun 10 2020 09:27:39 GMT-0400',
      createdBy: 'Denver Firth',
      subject: 'New Project',
      description:
        'I have pushed the initial architectural design flowcharts for the new project. Please, have a look and confirm that everything is in order.',
      priority: 'normal',
      status: 'open',
      department: 'Developers',
      logs: [],
      id: 'mPiDTX1',
    },
    {
      createdOn: 'Wed Jun 10 2020 10:56:05 GMT-0400',
      createdBy: 'Martin Maltais',
      subject: "Let's get this done!",
      description: 'This is time!',
      priority: 'normal',
      status: 'open',
      department: 'Sales',
      logs: [],
      id: '6gf0ZMi',
    },
  ],
};

export const INITIAL_STATE_DEPARTMENTS = {
  departments: [
    {
      id: '1',
      name: 'Direction',
      description: "We're not leaders, but simple facilitators.",
      extension: '0000',
      email: 'direction@yourdomain.com',
      slug: 'direction',
      picture: directionImg,
    },
    {
      id: '2',
      name: 'Accounting',
      description: 'Because numbers are not only that, but always more.',
      extension: '55556',
      slug: 'accounting',
      picture: accountingImg,
    },
    {
      id: '3',
      name: 'Human Resources',
      description: 'Building a family, one employee at a time.',
      extension: '4444',
      email: 'humanresources@yourdomain.com',
      slug: 'human-resources',
      picture: humanResourcesImg,
    },
    {
      id: '4',
      name: 'Developers',
      description: 'We take pride in our architecture and clean code.',
      extension: '7541',
      email: 'devs@yourdomain.com',
      slug: 'developers',
      picture: developersImg,
    },
    {
      id: '5',
      name: 'Sales',
      description: 'We find the best solutions for all our partners.',
      extension: '2222',
      email: 'sales@yourdomain.com',
      slug: 'sales',
      picture: salesImg,
    },
    {
      id: '6',
      name: 'Customer Care',
      description:
        'We take pride in caring for each and every partners we listen to.',
      extension: '3333',
      email: 'customercare@yourdomain.com',
      slug: 'customer-care',
      picture: customerCareImg,
    },
    {
      id: '7',
      name: 'Marketing',
      description:
        'We are not only designers. Ultimately, we are people reachers.',
      extension: '1111',
      email: 'marketing@yourdomain.com',
      slug: 'marketing',
      picture: marketingImg,
    },
  ],
};

export const INITIAL_STATE_USERS = {
  users: [
    {
      id: '16',
      name: 'Julia Tyrone',
      gender: 'Female',
      email: 'julityrone@yourdomain.com',
      role: 'Manager',
      department: 'Sales',
      picture: 'https://randomuser.me/api/portraits/women/5.jpg',
    },
    {
      picture: 'https://randomuser.me/api/portraits/men/10.jpg',
      name: 'Denver Firth',
      gender: 'Male',
      role: 'Manager',
      department: 'Developers',
      id: '17',
    },
    {
      id: '18',
      name: 'Trevor Holds',
      gender: 'Male',
      email: 'trevorholds@yourdomain.com',
      role: 'Manager',
      department: 'Marketing',
      picture: 'https://randomuser.me/api/portraits/men/15.jpg',
    },
    {
      picture: 'https://randomuser.me/api/portraits/men/20.jpg',
      name: 'Martin Maltais',
      gender: 'Male',
      role: 'User',
      department: 'Sales',
      id: '19',
    },
    {
      picture: 'https://randomuser.me/api/portraits/men/25.jpg',
      name: 'Joey Trebionny',
      gender: 'Male',
      role: 'Manager',
      department: 'Sales',
      id: '20',
    },
    {
      id: '21',
      name: 'Melissa Tender',
      gender: 'Female',
      email: 'melissatender@yourdomain.com',
      role: 'Manager',
      department: 'Customer Care',
      picture: 'https://randomuser.me/api/portraits/women/30.jpg',
    },
    {
      id: '22',
      name: 'Sylvio Gutry',
      gender: 'Male',
      email: 'sylviogutry@yourdomain.com',
      role: 'User',
      department: 'Marketing',
      picture: 'https://randomuser.me/api/portraits/men/35.jpg',
    },
    {
      id: '23',
      name: 'Lana Bellgrade',
      gender: 'Female',
      email: 'lanabelgrade@yourdomain.com',
      role: 'Manager',
      department: 'Marketing',
      picture: 'https://randomuser.me/api/portraits/women/40.jpg',
    },
    {
      id: '24',
      name: 'Ian McGarreth',
      gender: 'Male',
      email: 'ianmcgarreth@yourdomain.com',
      role: 'User',
      department: 'Sales',
      picture: 'https://randomuser.me/api/portraits/men/45.jpg',
    },
    {
      picture: 'https://randomuser.me/api/portraits/men/50.jpg',
      name: 'Martin Hutt',
      gender: 'Male',
      role: 'User',
      department: 'Customer Care',
      id: '25',
    },
    {
      id: '26',
      name: 'Deborah Hill',
      gender: 'Female',
      role: 'Administrator',
      email: 'admin@yourdomain.com',
      department: 'Direction',
      picture: 'https://randomuser.me/api/portraits/women/55.jpg',
    },
  ],
};
